### ISSUE TITLE
搜图谱也说未找到但

### ISSUE THREAD

**Issue by Thirace446** [whiterasbk/MiraiQueryPokemon#2]
![333](https://user-images.githubusercontent.com/55902963/202352344-b0800490-57df-44ae-9ae2-c0fc6b85ce95.png)
![444](https://user-images.githubusercontent.com/55902963/202352350-916a2592-e58d-426c-bff4-e44c0ec3d09b.png)

**Comment by whiterasbk** [comment]
应该放在data目录而不是config

**Comment by Thirace446** [comment]
2022-11-18 01:21:34 I/bot.good.  QueryPokemon: query pokemon loaded
2022-11-18 01:21:34 W/stderr: Warning: Nashorn engine is planned to be removed from a future JDK release
2022-11-18 01:21:34 I/bot.good.  QueryPokemon: [loaded script: script.js]
2022-11-18 01:21:34 I/bot.good.  QueryPokemon: [loaded mapper: egg_group.yml]
2022-11-18 01:21:34 I/bot.good.  QueryPokemon: [loaded mapper: public.yml]
2022-11-18 01:21:34 I/bot.good.  QueryPokemon: [loaded mapper: stats_abbreviation.yml]
2022-11-18 01:21:35 I/bot.good.  QueryPokemon: [loaded mapper script: mapper.js]
2022-11-18 01:21:35 E/bot.good.  QueryPokemon: java.lang.NoClassDefFoundError: io/ktor/client/features/HttpTimeout
java.lang.NoClassDefFoundError: io/ktor/client/features/HttpTimeout
at QueryPokemon-0.0.1.jar//bot.good.QueryExecutable$Companion$httpClient$1.invoke(QueryExecutable.kt:163)
at QueryPokemon-0.0.1.jar//bot.good.QueryExecutable$Companion$httpClient$1.invoke(QueryExecutable.kt:162)
at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:40)
at QueryPokemon-0.0.1.jar//bot.good.QueryExecutable.<clinit>(QueryExecutable.kt:162)
at QueryPokemon-0.0.1.jar//bot.good.QueryPokemon.onEnable(QueryPokemon.kt:59)
at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:279)
at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:175)
at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:336)
at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:194)
at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
at org.itxtech.mcl.Loader.start(Loader.java:194)
at org.itxtech.mcl.Loader.main(Loader.java:84)

**Comment by whiterasbk** [comment]
@Thirace446 请提供mirai版本

**Comment by Thirace446** [comment]
2.13.0RC2
